/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/trabaja-con-nosotros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/trabaja-con-nosotros'
  id:
    | '__root__'
    | '/'
    | '/politica-de-privacidad'
    | '/terminos-y-condiciones'
    | '/trabaja-con-nosotros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
